ERROR 2019-02-25 11:40:52,316 exceptions 27 [<users.views.RegisterCreateView object at 0x10fce3400>] Got AttributeError when attempting to get a value for field `allow` on serializer `RegisterSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `User` instance.
Original exception text was: 'User' object has no attribute 'allow'.
ERROR 2019-02-25 19:10:11,612 views 45 access_token获取失败
ERROR 2019-02-25 19:10:11,618 views 45 access_token获取失败
ERROR 2019-02-25 19:10:44,652 views 45 access_token获取失败
ERROR 2019-02-25 19:10:54,677 exceptions 28 [<oauth.views.QQAuthUserView object at 0x1103b5278>] dump() missing 1 required positional argument: 'f'
ERROR 2019-02-25 19:13:49,637 views 45 access_token获取失败
ERROR 2019-02-25 19:14:25,327 exceptions 28 [<oauth.views.QQAuthUserView object at 0x10ee06c88>] dump() missing 1 required positional argument: 'f'
ERROR 2019-02-25 19:15:55,369 views 45 access_token获取失败
ERROR 2019-02-25 19:18:58,565 views 45 access_token获取失败
ERROR 2019-02-25 19:20:19,072 views 45 access_token获取失败
ERROR 2019-02-25 19:20:27,162 views 45 access_token获取失败
ERROR 2019-02-25 19:20:36,327 exceptions 28 [<oauth.views.QQAuthUserView object at 0x10b1ab4e0>] dump() missing 1 required positional argument: 'f'
ERROR 2019-02-25 19:21:29,685 views 45 access_token获取失败
ERROR 2019-02-25 19:22:25,254 views 43 name 'oauth' is not defined
ERROR 2019-02-27 10:17:23,066 exceptions 28 [<oauth.views.QQAuthUserView object at 0x10c2007b8>] dump() missing 1 required positional argument: 'f'
ERROR 2019-02-27 10:21:52,888 views 45 access_token获取失败
ERROR 2019-02-27 10:26:56,938 views 45 access_token获取失败
ERROR 2019-02-27 10:57:11,823 exceptions 28 [<users.views.BindEmailApiView object at 0x11300e390>] get_object() missing 1 required positional argument: 'req'
ERROR 2019-02-27 11:02:10,746 exceptions 28 [<users.views.BindEmailApiView object at 0x10dd0c6d8>] 'Request' object has no attribute 'header'
ERROR 2019-02-27 11:04:28,720 exceptions 28 [<users.views.BindEmailApiView object at 0x10a74f2e8>] Invalid token type. Token must be a <class 'bytes'>
ERROR 2019-02-27 11:11:16,079 exceptions 28 [<users.views.BindEmailApiView object at 0x10ac5f4e0>] Cannot call `.is_valid()` as no `data=` keyword argument was passed when instantiating the serializer instance.
ERROR 2019-02-27 11:13:32,470 exceptions 28 [<users.views.BindEmailApiView object at 0x10c62af28>] 'bytes' object is not callable
ERROR 2019-02-27 11:16:30,871 exceptions 28 [<users.views.BindEmailApiView object at 0x113274160>] ("Creating a ModelSerializer without either the 'fields' attribute or the 'exclude' attribute has been deprecated since 3.3.0, and is now disallowed. Add an explicit fields = '__all__' to the BindEmailSerializer serializer.",)
ERROR 2019-02-27 11:17:46,840 exceptions 28 [<users.views.BindEmailApiView object at 0x1054f4f98>] `update()` did not return an object instance.
ERROR 2019-02-27 11:18:06,857 exceptions 28 [<users.views.BindEmailApiView object at 0x110510e10>] `update()` did not return an object instance.
ERROR 2019-02-27 11:49:18,666 exceptions 28 [<users.views.BindEmailApiView object at 0x10e92a6d8>] 'ReturnDict' object has no attribute 'email'
ERROR 2019-02-27 14:33:04,177 exceptions 28 [<users.views.EmailApiView object at 0x10d929da0>] 'dict' object has no attribute 'generate_verify_email_address'
ERROR 2019-02-27 14:33:04,178 exceptions 28 [<users.views.EmailApiView object at 0x10dcbfd68>] 'dict' object has no attribute 'generate_verify_email_address'
ERROR 2019-02-27 14:34:28,450 exceptions 28 [<users.views.EmailApiView object at 0x109250550>] dump() missing 1 required positional argument: 'f'
ERROR 2019-02-27 14:47:45,599 exceptions 28 [<users.views.UserInfoApiView object at 0x10da2add8>] Invalid token type. Token must be a <class 'bytes'>
ERROR 2019-02-27 14:48:03,895 exceptions 28 [<users.views.UserInfoApiView object at 0x10dbb0860>] Invalid token type. Token must be a <class 'bytes'>
ERROR 2019-02-27 14:49:13,623 exceptions 28 [<users.views.UserInfoApiView object at 0x10dbb6748>] Invalid token type. Token must be a <class 'bytes'>
ERROR 2019-02-27 14:50:48,879 exceptions 28 [<users.views.EmailApiView object at 0x110f68be0>] 'QueryDict' object is not callable
ERROR 2019-02-27 14:51:07,648 exceptions 28 [<users.views.EmailApiView object at 0x11105cb00>] 'QueryDict' object is not callable
ERROR 2019-02-27 14:51:58,587 exceptions 28 [<users.views.EmailApiView object at 0x107abea20>] maximum recursion depth exceeded while calling a Python object
ERROR 2019-02-27 19:09:27,087 exceptions 28 [<areas.views.AreaViewSet object at 0x10fe0eb70>] 'AreaViewSet' should either include a `queryset` attribute, or override the `get_queryset()` method.
ERROR 2019-02-27 19:26:41,264 exceptions 28 [<areas.views.AreaViewSet object at 0x10ec74908>] 'Area' object is not iterable
ERROR 2019-02-27 19:26:44,065 exceptions 28 [<areas.views.AreaViewSet object at 0x10fb0f4a8>] 'Area' object is not iterable
ERROR 2019-02-27 19:27:03,549 exceptions 28 [<areas.views.AreaViewSet object at 0x10fbb1f28>] 'Area' object is not iterable
ERROR 2019-02-27 19:27:31,684 exceptions 28 [<areas.views.AreaViewSet object at 0x10fb29160>] 'Area' object is not iterable
ERROR 2019-02-27 19:28:09,917 exceptions 28 [<areas.views.AreaViewSet object at 0x10d5758d0>] 'Area' object is not iterable
ERROR 2019-02-27 19:31:18,974 exceptions 28 [<areas.views.ShiApiView object at 0x10ba02e48>] 'AreaSerializer' object is not callable
ERROR 2019-02-27 19:31:25,590 exceptions 28 [<areas.views.ShiApiView object at 0x10bc12668>] 'ShiApiView' object has no attribute 'pk'
ERROR 2019-02-27 19:31:39,501 exceptions 28 [<areas.views.ShiApiView object at 0x10bc26eb8>] 'ShiApiView' object has no attribute 'pk'
ERROR 2019-02-27 19:31:49,465 exceptions 28 [<areas.views.ShiApiView object at 0x10bc8da20>] 'ShiApiView' object has no attribute 'pk'
ERROR 2019-02-27 19:32:38,993 exceptions 28 [<areas.views.ShiApiView object at 0x10567eda0>] invalid literal for int() with base 10: 'pk'
ERROR 2019-02-27 19:32:39,875 exceptions 28 [<areas.views.ShiApiView object at 0x1057f6f28>] invalid literal for int() with base 10: 'pk'
ERROR 2019-02-27 19:32:40,264 exceptions 28 [<areas.views.ShiApiView object at 0x105803828>] invalid literal for int() with base 10: 'pk'
ERROR 2019-02-27 19:32:40,459 exceptions 28 [<areas.views.ShiApiView object at 0x10588bc88>] invalid literal for int() with base 10: 'pk'
ERROR 2019-02-27 19:33:54,006 exceptions 28 [<areas.views.ShiApiView object at 0x1047a9940>] get() returned more than one Area -- it returned 2!
ERROR 2019-02-27 19:34:02,781 exceptions 28 [<areas.views.ShiApiView object at 0x10488f860>] get() returned more than one Area -- it returned 2!
ERROR 2019-02-27 19:34:04,841 exceptions 28 [<areas.views.ShiApiView object at 0x10486eb38>] get() returned more than one Area -- it returned 2!
ERROR 2019-02-27 19:35:53,698 exceptions 28 [<areas.views.ShiApiView object at 0x11053ada0>] 'AreaSerializer' object is not callable
ERROR 2019-02-27 19:35:57,103 exceptions 28 [<areas.views.ShiApiView object at 0x1105c6cc0>] 'AreaSerializer' object is not callable
ERROR 2019-02-27 19:36:04,723 exceptions 28 [<areas.views.ShiApiView object at 0x10fd18048>] 'AreaSerializer' object is not callable
ERROR 2019-02-27 19:36:41,411 exceptions 28 [<areas.views.ShiApiView object at 0x110728da0>] 'AreaSerializer' object is not callable
ERROR 2019-02-27 19:36:42,261 exceptions 28 [<areas.views.ShiApiView object at 0x1107eee80>] 'AreaSerializer' object is not callable
ERROR 2019-02-27 19:44:14,780 exceptions 28 [<areas.views.ShiApiView object at 0x112f9d940>] get() got an unexpected keyword argument 'id'
ERROR 2019-02-27 19:44:16,317 exceptions 28 [<areas.views.ShiApiView object at 0x11300a438>] get() got an unexpected keyword argument 'id'
ERROR 2019-02-27 19:50:59,860 exceptions 28 [<areas.views.AreaApiView object at 0x10e663c88>] invalid literal for int() with base 10: ''
ERROR 2019-02-27 19:51:00,818 exceptions 28 [<areas.views.AreaApiView object at 0x10e7d8748>] invalid literal for int() with base 10: ''
ERROR 2019-02-28 11:12:35,164 exceptions 28 [<areas.views.AddressModelViewSet object at 0x104a73be0>] (1146, "Table 'mall_meiduo.address' doesn't exist")
ERROR 2019-02-28 11:12:36,357 exceptions 28 [<areas.views.AddressModelViewSet object at 0x104ad1f98>] (1146, "Table 'mall_meiduo.address' doesn't exist")
ERROR 2019-02-28 11:12:36,799 exceptions 28 [<areas.views.AddressModelViewSet object at 0x104b172b0>] (1146, "Table 'mall_meiduo.address' doesn't exist")
ERROR 2019-02-28 11:12:36,981 exceptions 28 [<areas.views.AddressModelViewSet object at 0x104b2e390>] (1146, "Table 'mall_meiduo.address' doesn't exist")
ERROR 2019-02-28 11:12:37,169 exceptions 28 [<areas.views.AddressModelViewSet object at 0x104b17080>] (1146, "Table 'mall_meiduo.address' doesn't exist")
ERROR 2019-02-28 11:12:37,360 exceptions 28 [<areas.views.AddressModelViewSet object at 0x104b2eef0>] (1146, "Table 'mall_meiduo.address' doesn't exist")
ERROR 2019-02-28 11:12:37,516 exceptions 28 [<areas.views.AddressModelViewSet object at 0x104b49f60>] (1146, "Table 'mall_meiduo.address' doesn't exist")
ERROR 2019-02-28 11:12:37,699 exceptions 28 [<areas.views.AddressModelViewSet object at 0x104b2e208>] (1146, "Table 'mall_meiduo.address' doesn't exist")
ERROR 2019-02-28 11:53:31,586 exceptions 28 [<areas.views.AddressModelViewSet object at 0x105d79438>] Cannot set both 'fields' and 'exclude' options on serializer AddressModelSerializers.
ERROR 2019-02-28 11:53:43,619 exceptions 28 [<areas.views.AddressModelViewSet object at 0x107a823c8>] (1048, "Column 'user_id' cannot be null")
ERROR 2019-02-28 11:53:45,007 exceptions 28 [<areas.views.AddressModelViewSet object at 0x107b4f9e8>] (1048, "Column 'user_id' cannot be null")
ERROR 2019-02-28 11:54:55,729 exceptions 28 [<areas.views.AddressModelViewSet object at 0x1123a3908>] `create()` did not return an object instance.
ERROR 2019-02-28 12:07:13,570 exceptions 28 [<areas.views.AddressModelViewSet object at 0x10a7ab588>] Cannot assign "True": "Address.area" must be a "Area" instance.
ERROR 2019-02-28 12:10:29,539 exceptions 28 [<areas.views.AddressModelViewSet object at 0x10b408518>] (1452, 'Cannot add or update a child row: a foreign key constraint fails (`mall_meiduo`.`address`, CONSTRAINT `address_area_id_6f54a149_fk_areas_id` FOREIGN KEY (`area_id`) REFERENCES `areas` (`id`))')
ERROR 2019-02-28 12:10:30,547 exceptions 28 [<areas.views.AddressModelViewSet object at 0x10b4d6d30>] (1452, 'Cannot add or update a child row: a foreign key constraint fails (`mall_meiduo`.`address`, CONSTRAINT `address_area_id_6f54a149_fk_areas_id` FOREIGN KEY (`area_id`) REFERENCES `areas` (`id`))')
ERROR 2019-02-28 12:10:30,972 exceptions 28 [<areas.views.AddressModelViewSet object at 0x10b530390>] (1452, 'Cannot add or update a child row: a foreign key constraint fails (`mall_meiduo`.`address`, CONSTRAINT `address_area_id_6f54a149_fk_areas_id` FOREIGN KEY (`area_id`) REFERENCES `areas` (`id`))')
ERROR 2019-02-28 12:19:12,931 exceptions 28 [<areas.views.AddressModelViewSet object at 0x1114e6748>] You must call `.is_valid()` before calling `.save()`.
ERROR 2019-02-28 12:22:00,913 exceptions 28 [<areas.views.AddressModelViewSet object at 0x10e7ca710>] Cannot call `.is_valid()` as no `data=` keyword argument was passed when instantiating the serializer instance.
ERROR 2019-02-28 12:22:02,130 exceptions 28 [<areas.views.AddressModelViewSet object at 0x10e8b5ac8>] Cannot call `.is_valid()` as no `data=` keyword argument was passed when instantiating the serializer instance.
ERROR 2019-02-28 12:22:02,470 exceptions 28 [<areas.views.AddressModelViewSet object at 0x10e95def0>] Cannot call `.is_valid()` as no `data=` keyword argument was passed when instantiating the serializer instance.
ERROR 2019-02-28 12:24:08,558 exceptions 28 [<areas.views.AddressModelViewSet object at 0x103babda0>] 'NoneType' object has no attribute 'user_id'
ERROR 2019-02-28 12:24:08,561 exceptions 28 [<areas.views.AddressModelViewSet object at 0x1039715f8>] 'NoneType' object has no attribute 'user_id'
ERROR 2019-02-28 12:28:38,385 exceptions 28 [<areas.views.AddressModelViewSet object at 0x109035518>] 'User' object has no attribute 'user_id'
ERROR 2019-02-28 12:28:54,535 exceptions 28 [<areas.views.AddressModelViewSet object at 0x10b171320>] 'User' object has no attribute 'get'
ERROR 2019-02-28 12:33:37,614 exceptions 28 [<areas.views.AddressModelViewSet object at 0x1130276a0>] 'User' object has no attribute 'user_id'
